version: "3.7"
services:
  proxy:
    image: ubuntu/squid
    ports:
      - "8128:3128"
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  https-web:
    image: nginx:latest
    ports:
      - "8443:443"
    volumes:
      - ./https-web/default.conf:/etc/nginx/conf.d/default.conf
