; Example sketch for HttpClient_ESP32_Lib
[platformio]
default_envs = m5stack-atom

[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3
lib_extra_dirs = ../..
lib_deps =
